# Generated by Django 2.2.12 on 2020-05-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='awards',
            field=models.TextField(verbose_name='Awards'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='education',
            field=models.TextField(verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='experience',
            field=models.TextField(verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='header',
            field=models.TextField(verbose_name='Header'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='skills_interests',
            field=models.TextField(verbose_name='Skills and Interests'),
        ),
    ]
